---
jobs:  
- name: unit tests
  public: true
  plan:
  - get: git-deals
    trigger: true
  - task: bundle
    file: git-deals/concourse/task_bundle.yml
  - task: unit tests
    file: git-deals/concourse/task_unit.yml

- name: functional tests
  public: true
  serial: true
  plan:
  - get: git-deals
    trigger: true
    passed: ['unit tests']
  - task: bundle
    file: git-deals/concourse/task_bundle.yml
  - task: deploy to test space
    file: git-deals/concourse/task_deploy_test.yml
    config:
      params:
        CF_SPACE: test
        CF_USERNAME: {{cf_username}}
        CF_PASSWORD: {{cf_password}}


resources:  
- name: git-deals
  type: git
  source:
    uri: https://github.com/moredip/pretend_deals_service.git
    branch: concourse
    check_every: 10s
