---
jobs:  
- name: deploy to env
  serial: true
  plan:
  - get: git-pricing
    trigger: true

  - task: simulated-deployment
    config:
      platform: linux
      image: docker:///ruby#2
      run: 
        path: "sh"
        args: 
          - "-c"
          - |
              set -e
              DEPLOY_UID=$(ruby -r securerandom -e "print SecureRandom.uuid.split('-').first")
              DISPOSABLE_ENV_NAME=some_app__${DEPLOY_UID}
              echo PRETENDING TO DEPLOY TO $DISPOSABLE_ENV_NAME
              mkdir -p pool
              echo 'my-lock-name' > pool/name
              echo $DISPOSABLE_ENV_NAME > pool/metadata
              sleep 5
              echo ALL DONE

  - put: test-environments
    params:
      add: simulated-deployment/pool
  - put: test-environments
    params:
      claim: my-lock-name

- name: test against env
  plan:
  - get: test-environments
    trigger: true
    passed: [deploy to env]
  - task: simulated-test
    config:
      platform: linux
      image: docker:///ruby#2
      inputs:
        - name: test-environments
      run: 
        path: "sh"
        args: 
          - "-c"
          - |
              set -e
              DISPOSABLE_ENV_NAME=$(cat test-environments/metadata)
              echo PRETENDING TO TEST MY DEPLOYMENT AT $DISPOSABLE_ENV_NAME...
              sleep 5
              echo ALL DONE
  - put: test-environments
    params: {remove: test-environments}

resources:  
- name: git-pricing
  type: git
  source:
    uri: https://github.com/moredip/pretend_pricing_service.git
    branch: concourse
    check_every: 10s

- name: test-environments
  type: pool
  source:
    uri: git@github.com:moredip/concourse-build.git
    branch: locks
    pool: test-env
    private_key: {{github_deploy_key}}
