---
jobs:  
- name: unit tests
  public: true
  plan:
  - get: git-pricing
    trigger: true
  - task: bundle
    file: git-pricing/concourse/task_bundle.yml
  - task: unit tests
    file: git-pricing/concourse/task_unit.yml

- name: deploy test env
  public: true
  serial: true
  plan:
  - get: git-pricing
    trigger: true
    passed: ['unit tests']

  - task: bundle
    file: git-pricing/concourse/task_bundle.yml

  - task: deploy
    file: git-pricing/concourse/task_deploy.yml
    config:
      params:
        CF_USERNAME: {{cf_username}}
        CF_PASSWORD: {{cf_password}}

  - put: test-environments
    params:
      add: deploy/concourse_pool
  - put: test-environments
    params:
      claim: cf-test-env

- name: test against env
  plan:
  - get: test-environments
    trigger: true
    passed: [deploy test env]
  - get: git-pricing
    passed: [deploy test env]

  - task: bundle
    file: git-pricing/concourse/task_bundle.yml

  - task: functional tests
    file: git-pricing/concourse/task_functional_tests.yml
    ensure:
      do:
        - task: teardown disposable stack
          file: git-pricing/concourse/task_teardown.yml
          config:
            params:
              CF_USERNAME: {{cf_username}}
              CF_PASSWORD: {{cf_password}}

        - put: test-environments
          params: {remove: test-environments}



resources:  
- name: git-pricing
  type: git
  source:
    uri: https://github.com/moredip/pretend_pricing_service.git
    branch: concourse
    check_every: 10s
    private_key: {{github_deploy_key}}

- name: test-environments
  type: pool
  source:
    uri: git@github.com:moredip/concourse-build.git
    branch: locks
    pool: test-env
    private_key: {{github_deploy_key}}
